service: music-wheel-api
frameworkVersion: ">=4.2.5"

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  api:
    handler: bin/main
    events:
      - http:
          path: albums/upload
          method: post
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: albums/{id}
          method: get
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: albums
          method: get
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: albums/{id}
          method: put
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: albums/{id}
          method: delete
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: user/signup
          method: post
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: user/settings
          method: get
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: user/settings
          method: put
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: user/settings/{id}
          method: delete
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false
      - http:
          path: presigned-url
          method: post
          cors:
            origin:
              - https://music-dashboard-jade.vercel.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - UserID
            allowCredentials: false

package:
  patterns:
    - "!*/**"
    - "bin/main"
